IF SCHEMA_ID(N'settlement') IS NULL EXEC (N'CREATE SCHEMA settlement');
IF DATABASE_PRINCIPAL_ID(N'swiftbets_app') IS NULL EXEC (N'CREATE ROLE swiftbets_app');
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::settlement TO swiftbets_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::inbox TO swiftbets_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::outbox TO swiftbets_app;
